---
name: CI
on: [ push, pull_request ]
jobs:
  nix-channel-deploy:
    needs: omnilint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/nix-channel-build
        env:
          NIX_CACHE_PRIV_KEY: ${{ secrets.NIX_CACHE_PRIV_KEY }}
