---
name: CI
on: [ push, pull_request ]
jobs:
  nix-channel-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - env:
          NIX_CACHE_PRIV_KEY: ${{ secrets.NIX_CACHE_PRIV_KEY }}
        run: |
          set -e -x -o pipefail
          mkdir -p "result/cache"
          : Create channel files
          tar -cJf "result/nixexprs.tar.xz" ./*.nix \
              --transform "s,^,${PWD##*/}/," \
              --owner=0 --group=0 --mtime="1970-01-01 00:00:00 UTC"
          touch "result/index.html"
          printf 'https://nix.hydro.ac/cache' > "result/binary-cache-url"
          : Build
          mapfile -t OUT_PATHS < <( nix-build )
          : Populate cache
          export NIX_SECRET_KEY_FILE="$PWD/nix-cache-priv-key.pem"
          echo "$NIX_CACHE_PRIV_KEY" >"$NIX_SECRET_KEY_FILE"
          nix store sign -k "$NIX_SECRET_KEY_FILE" "${OUT_PATHS[@]}" --no-use-registries --derivation hydro
          nix copy --to "file:///$PWD/result/cache" "${OUT_PATHS[@]}"
          nix path-info --store "file:///$PWD/result/cache" --json
          : Done
      - name: Setup Pages
        if: github.ref == 'refs/heads/master'
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        if: github.ref == 'refs/heads/master'
        with:
          path: 'result'
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        id: deployment
        uses: actions/deploy-pages@main
